export interface Plan{
  id:number,
  name:string,
  description1:string,
  description2:string,
  description3:string,
  description4:string,
  description5:string,
  description6:string,
  description7:string,
  description8:string,
  maxNumberRepository:number,
  maxNumberProject:number,
  price:number,
  image:string,
}
